### ISSUE TITLE
Start script not used for Yarn buildpack

### ISSUE THREAD

**Issue by coffee-cup** [heroku/buildpacks-nodejs#183]
When building projects with Yarn (`yarn.lock` detected), the start script in `package.json` is not used to start the container. However, when using NPM (`package-lock.json` detected), the start script is used. I would expect that these behaviours match and that the start script is always used as the default way to start the container.

We've only noticed this become an issue on the latest version of the Heroku buildpacks 20.

**Comment by joshwlewis** [comment]
This was fixed in https://github.com/heroku/buildpacks-nodejs/pull/214. Be on the lookout for the next release of `heroku/buildpacks:20` which should fix the issue for you.
