### ISSUE TITLE
Node.js app's "start" script not used anymore

### ISSUE THREAD

**Issue by jeromegn** [heroku/buildpacks-nodejs#211]
Since #184, it looks like a node.js project needs a Procfile so that the buildpack finds its launch command.

Since about 3 hours ago (coincidentally, as this was merged: https://github.com/heroku/pack-images/pull/231), our automated tests started failing. These tests use a very basic, no dependencies, `package.json` that looks like this:

```json
{
    "name": "hello-node",
    "version": "1.0.0",
    "main": "index.js",
    "scripts": {
        "start": "node index.js"
    }
}
```

Ever since this change, we started seeing:

```
ERROR: failed to launch: determine start command: when there is no default process a command is required
```

We've resolved this by adding a Procfile like:

```procfile
web: npm start
```

Is this change intentional?

**Comment by backflip** [comment]
@jeromegn, thanks for the workaround! I found this when trying to understand why my fly.io deployment did not work anymore. :)

**Comment by inudge** [comment]
Had the same problem, thanks !

**Comment by joshwlewis** [comment]
Thanks for the report. This was not intentional.

With your example, I see that the `web` process is set:

```bash
pack inspect hello-node
Inspecting image: hello-node

REMOTE:
(not present)

LOCAL:

Stack: heroku-20

Base Image:
  Reference: adba7eea84bbc01ddfd5e0b5f6a6f6548bd61c799750b64c674499106c8efcb8
  Top Layer: sha256:f06bdf2f5c2b7467979b9bb60a8c8c52fde3a0bfad78779f7d879b7d222ad6f0

Run Images:
  heroku/pack:20

Buildpacks:
  ID                          VERSION        HOMEPAGE
  heroku/nodejs-engine        0.8.0          https://github.com/heroku/buildpacks-nodejs
  heroku/nodejs-npm           0.5.0          https://github.com/heroku/buildpacks-nodejs
  heroku/procfile             0.6.2          -

Processes:
  TYPE        SHELL        COMMAND        ARGS
  web         bash         npm start
```

The unintended change here is that `web` is no longer flagged as default.
