### ISSUE TITLE
version is now required in package.json

### ISSUE THREAD

**Issue by ipmb** [heroku/buildpacks-nodejs#212]
This appears to be a regression (or undocumented change) from #184 

Projects without a `version` defined in `package.json` will fail to build with the following error:

```
  ===> BUILDING
  
  [Heroku Node.js Engine Buildpack]
  
  [Checking Node.js version]
  
  [Error: Node.js engine package.json error]
  Couldn't parse package.json: Could not parse package.json: missing field `version` at line 78 column 1
  ERROR: failed to build: exit status 42
  ERROR: failed to build: executing lifecycle: failed with status code: 145
```

**Comment by joshwlewis** [comment]
Yes, you are correct. I'd call this a regression. I'll get a fix in for this.

For anyone else with this issue, the temporary workaround would be to set a semver compatible `version` in `package.json` like this:

```json
{
  "name": "example-app",
  "version": "0.0.0"
}
```
