### ISSUE TITLE
regression bug: Couldn't resolve Node.js version

### ISSUE THREAD

**Issue by alexanderniebuhr** [heroku/buildpacks-nodejs#223]
we do use `heroku/buildpacks:20` with `pack` in our GitHub CI Pipeline (following command)

`pack build ghcr.io/frickegroup/xxxx --no-color --path components/function --builder heroku/buildpacks:20 --publish`

However started 5days ago, it always fails to deploy with the message `Couldn't resolve Node.js version: 17.8.0`

```
===> DETECTING
heroku/nodejs-engine 0.8.0
heroku/nodejs-npm    0.5.0
heroku/procfile      0.6.2
===> RESTORING
===> BUILDING

[Heroku Node.js Engine Buildpack]

[Checking Node.js version]
Detected Node.js version range: 17.8.0

[Error: Node.js engine version error]
Couldn't resolve Node.js version: 17.8.0
ERROR: failed to build: exit status 43
ERROR: failed to build: executing lifecycle: failed with status code: 51
```
---
if we hard set the version of the `heroku/nodejs` buildpack to  0.4.x (following command)

`pack build ghcr.io/frickegroup/xxxx --no-color --path components/function --builder heroku/buildpacks:20 --buildpack heroku/nodejs@0.4.2 --publish`

the pipeline is running without any issues, like we expect.

```
===> DETECTING
heroku/nodejs-engine 0.7.5
heroku/nodejs-npm    0.5.0
heroku/procfile      0.6.2
===> RESTORING
===> BUILDING
[INFO] Node.js Buildpack
[INFO] Installing toolbox
[INFO] - yj

[Installing Node]
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v17.8.0
[INFO] Setting NODE_ENV to production
```

**Comment by joshwlewis** [comment]
Ok, yeah. I see the issue, we use a static list of available node versions here: https://github.com/heroku/buildpacks-nodejs/blob/main/buildpacks/nodejs-engine/inventory.toml. 17.8.0 was evidently released after the last inventory update. I'll get a PR in.
