### ISSUE TITLE
Yarn2+ Broken after PR#201

### ISSUE THREAD

**Issue by zenchild** [heroku/buildpacks-nodejs#246]
PR #201 introduced a regression for Yarn2 (or 3 in our case). What was previously a successful build, now errors out with the following when it gets to the yarn buildpack:

```
---> Installing node modules from ./yarn.lock
Unknown Syntax Error: Invalid option name ("--production=false").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

I am able to work around this for now by specifying a version for the `heroku/nodejs-yarn` builldpack.

So, this is currently broken:
```
pack build myproj -v \
    -B "heroku/buildpacks:20" \
    -b "heroku/nodejs,heroku/ruby" \
    -p .
```

But this works around my issue:
```
pack build myproj -v \
    -B "heroku/buildpacks:20" \
    -b "heroku/nodejs-engine,heroku/nodejs-yarn@0.2.1,heroku/ruby" \
    -p .
```

**Comment by joshwlewis** [comment]
Thanks for the report. Indeed, this is not ideal for yarn 2 users.

**Comment by dtinth** [comment]
Since 3 months has passed without a fix from Heroku side, I am creating a corresponding issue on Yarn side, hoping that either party will be willing to work together to become more interoperable.

- https://github.com/yarnpkg/berry/issues/4608

**Comment by schabr06** [comment]
Is there any time table on when a fix for this will be introduced?

**Comment by tomh4** [comment]
This is still an issue...

**Comment by joshwlewis** [comment]
Yes, please keep your eye on #250, which should solve this.

**Comment by joshwlewis** [comment]
@zenchild - the new yarn buildpack shipped in #250. You might want to check that out.

**Comment by zenchild** [comment]
Thanks @joshwlewis ! I'll have a look.

**Comment by harmyderoman** [comment]
I started getting this error after February 9 in two different repos. 
For yarn 1, I fixed it by writing the exact version in `package.json`:
```
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": "1.21.1"
  },
```
For yarn 3, you must commit the yarn file to the GitHub repo.
The yarn file is located in `.yarn/releases/yarn-3.4.1.cjs`.
I hope it will help you!

**Comment by jagthedrummer** [comment]
@joshwlewis Can you recommend how one would take advantage of the changes in #250? I'm not finding anything there that indicates what changes should be made in a project.

**Comment by jagthedrummer** [comment]
I finally discovered that reordering our buildpacks did the trick. Having `heroku/nodejs` after `heroku/ruby` would trigger the `Invalid option name ("--production=false")` problem. But having `heroku/nodejs` first in the list fixed it.
