### ISSUE TITLE
Project fails to compile on ARM64

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpacks-nodejs#310]
Trying to compile the Rust buildpacks on my ARM64 MacBook M1 (eg via `cargo test`), I get:

```
error[E0425]: cannot find value `ARCH` in this scope
  --> common/nodejs-utils/src/inv.rs:45:45
   |
45 |         let platform = format!("{}-{}", OS, ARCH);
   |                                             ^^^^ not found in this scope
   |
help: consider importing this constant
   |
1  | use std::env::consts::ARCH;
   |
```

This is due to:
https://github.com/heroku/buildpacks-nodejs/blob/7454fbe32c820a9d55e449d22e1ce1591781d833/common/nodejs-utils/src/inv.rs#L18

Whilst that conditional is fine when cross-compiling, it breaks things when compiling for the host (eg `cargo check`, `cargo clippy`, `cargo test` workflows).

cc @joshwlewis @colincasey

**Comment by abarke** [comment]
Would be really great to see **arm64** arch supported by this buildpack. Perhaps an environment variable for now to select the target arch?

**Comment by edmorley** [comment]
@abarke Hi! So this issue as filed is for the problem that it's not possible to work on the buildpack (eg: compile it locally) on an ARM64 machine. Actually supporting ARM64 at runtime when the buildpack builds an app is a separate thing to solve - and will be much harder given that it will first need (a) support from Pack CLI/lifecycle, (b) ARM64 Heroku stack image variants (but that's also something that needs to be done carefully, see https://github.com/heroku/stack-images/issues/194).

**Comment by abarke** [comment]
Gotcha @edmorley I thought I was in the official heroku node.js buildpack. My apologies. 

In any case it would be great to see CNB support for multiple targets including arm64 and any future targets that may materialize.

**Comment by abarke** [comment]
@edmorley side question: would it be easy enough to add support for multiple runtime targets to the official heroku node.js buildpack? I have been experimenting with deploying node.js code to arm64 and it's going well. Up until now we just download a compatible node.js binary for arm64 and use that to run the app. Works a treat. The next step would be to either write our own buildpacks (not gonna happen) for app deployment, fork the official buildpack (plausible) or contribute to the official buildpack (ideal) and allow everyone to benefit, should Heroku support arm64 runtimes in the future.

**Comment by edmorley** [comment]
For languages where the buildpack uses the upstream binaries (like Node.js or Go do), adding support to the buildpack should be fairly easy - a conditional to just adjust the URL used etc. For languages where we have to build our own binaries, it will be a bit more involved, so likely not worth it until more of the rest of the CNB pieces support multi-arch. In addition, adding support to the buildpack first is actually necessary, since if we were say to add ARM64 Heroku stack image variants prior to that, any buildpack that wasn't architecture-aware would then start failing on alternate architectures.

**Comment by abarke** [comment]
> since if we were say to add ARM64 Heroku stack image variants prior to that, any buildpack that wasn't architecture-aware would then start failing on alternate architectures

Exactly, we already support a arm64 stack internally, so the missing piece for us is the buildpack. As the majority of our apps are Node.js we would be able to migrate the majority of our apps to ARM fairly efficiently. I will look into a PR for the buildpack to support an optional target for the downloaded node.js binary. That should be sufficient for our needs.
