### ISSUE TITLE
Cannot run nodejs-engine with empty object

### ISSUE THREAD

**Issue by schneems** [heroku/buildpacks-nodejs#371]
Previously in heroku/heroku-buildpacks-nodejs we're able to have a `package.json` with these contents:

```
{}
```

If you attempt to run this buildpack with those contents, you'll receive an error:

```
===> DETECTING
heroku/nodejs-engine 0.8.9
heroku/ruby          2.0.0
heroku/procfile      2.0.0
===> RESTORING
===> BUILDING

[Heroku Node.js Engine Buildpack]

[Checking Node.js version]
ERROR: failed to build: exit status 1


pack stderr:

[Error: Node.js engine package.json error]
Couldn't parse package.json: Could not parse package.json. missing field `name` at line 1 column 2
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

If it's not too much overhead, I would like to support building with an empty object in the `package.json` file. This will aid Ruby users who need a version of `node.js`.

**Comment by edmorley** [comment]
@schneems Creating a `package.json` should not be needed, see:
https://github.com/heroku/buildpacks-nodejs/blob/e1279b5ceae75b686f52512377b71ead6b0819f8/buildpacks/nodejs-engine/src/main.rs#L52-L57

ie: In your build plan require `node` iff you want the node engine buildpack to run. Then add the node engine buildpack as an `optional = true` buildpack in the Ruby meta-buildpack's detection group order.

**Comment by colincasey** [comment]
nice.  i'm glad that's the case @edmorley because it doesn't feel right to require an empty (or even minimal)`package.json` just to use `node` if your buildpack needs it.  

@schneems are you okay with this issue being closed?

**Comment by edmorley** [comment]
> an empty package.json is valid for the npm spec

As found on:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#name

> If you plan to publish your package, the most important things in your package.json are the name and version fields as they will be required.
> ...
> If you don't plan to publish your package, the name and version fields are optional.
