### ISSUE TITLE
The new deploy starts running before SIGTERM completed its job...

### ISSUE THREAD

**Issue by sayantan300** [heroku/buildpacks-nodejs#41]
I got a simple code, which sends notification to discord when app starts, and another one when app closes via `SIGTERM`.
Everything is fine, but the SIGTERM notification is sent after the new deploy starts, so my discord log messages shows like this:
![Screenshot_20210418-140842~2](https://user-images.githubusercontent.com/62213554/115139475-ab326800-a04f-11eb-9fdd-2a0baa67664a.png)

Currently my fix is to send the app starting signal after 1 sec (using `setTimeout()`).
Please look into this matter. (Even if it's not important, but it seems as if 2 instance would run for a small time (1 instance would be closing while the 2 nd/new instance would be starting up parallely))

**Comment by danielleadams** [comment]
@sayantan300 Is this for the Heroku Buildpack? If so, you'll want to open an Issue here: https://github.com/heroku/heroku-buildpack-nodejs/issues. These buildpacks aren't running on Heroku.

**Comment by sayantan300** [comment]
Oh ok
