### ISSUE TITLE
Failing yarn build does not fail the build

### ISSUE THREAD

**Issue by rainhead** [heroku/buildpacks-nodejs#97]
We have an issue with our SCSS that causes `yarn build` to return 2, and was missed because this did not fail our Heroku CI build. This seems like an issue with the buildpack and not, say, a configuration issue.

In case it helps:
https://gist.github.com/rainhead/0b94b0be5ae148455fa8b68e6eff6a4b

**Comment by rainhead** [comment]
Sorry, it's actually returning 0 on CI (the 2 value was failure for a different reason). Closing.

**Comment by edmorley** [comment]
@rainhead Hi! Glad you figured this out :-)

Worth noting for the future:
1. This repository is not currently used on Heroku (it's for the next-gen buildpacks which are still in development). The repository for the Heroku classic Node.js buildpack is: https://github.com/heroku/heroku-buildpack-nodejs
2. For support issues (ie: anything that's not a reproducible bug with minimal steps to reproduce), a support ticket is recommended over a GitHub issue (the GitHub issues are not as frequently monitored): https://help.heroku.com
